FROM amazoncorretto:11-alpine-jdk
MAINTAINER Amol.Chandurkar@gmail.com
COPY target/weather-api-springboot-0.0.1-SNAPSHOT.jar weather-api-springboot-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/weather-api-springboot-0.0.1-SNAPSHOT.jar"]